version: '3.8'  # Specify the version of Docker Compose

services:
  # Spring Boot Application Service
  app:
    image: app  # Use a pre-built image or build it from the Dockerfile
    build:
      context: .  # This builds the image from the Dockerfile in the current directory
      dockerfile: Dockerfile  # Dockerfile to use for building
    ports:
      - "8080:8080"  # Map port 8080 on the container to port 8080 on the host
    depends_on:
      - postgresdb # Ensure that the PostgreSQL service is started before the app
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres  # Point to the PostgreSQL container
      SPRING_DATASOURCE_USERNAME: postgresdb
      SPRING_DATASOURCE_PASSWORD: 8332288
    networks:
      - app-network  # Connect to the same network as the database

  # PostgreSQL Database Service
  postgres:
    image: postgres  # Use the official PostgreSQL image
    environment:
      POSTGRES_DB: postgresdb  # Database name
      POSTGRES_USER: postgresdb  # Default username
      POSTGRES_PASSWORD: 8332288  # Default password
    ports:
      - "5434:5432"  # Map port 5432 on the container to port 5432 on the host (using 5434 to avoid conflicts)
    volumes:
      - postgres-data:/var/lib/postgresql/data  # Persist data in a volume
    networks:
      - app-network  # Same network for both services

# Define the network for both services
networks:
  app-network:
    driver: bridge

# Define a named volume for PostgreSQL data persistence
volumes:
  postgres-data:
