bot:
  token: 7524788008:AAGcItw7DxDuUELLoDmO-nB-CnW_lQKfbWU # Bot token
  secret_token_for_webhook: uOSSV0HFzadbgby4tf6behLf5cp6c8iEz5xiRGV3KME7PH6IRTqmevYx9aze1ruk
  webhook_url: https://anh-chololithic-transitively.ngrok-free.dev

spring:
  application:
    name: water_delivery

  main:
    allow-circular-references: true

  jackson:
    time-zone: Asia/Tashkent

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/water_delivery_db
    username: postgres
    password: root123

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        use_sql_comments: true
        connection:
          characterEncoding: UTF-8

  sql:
    init:
      mode: always       # Always initialize schema on startup
      platform: postgres

  session:
    store-type: jdbc     # Store Spring Session data in database
    jdbc:
      initialize-schema: always  # Auto-create SPRING_SESSION tables

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 50MB
    session:
      timeout: 1h

  messages:
    basename: messages
    encoding: UTF-8
    cache-duration: 3600

distance:
  api:
    key: AIzaSyC_j-4_IPUad1H_OCLYXgbJ0sooww78usg

server:
  port: 8080
